[package]
name = "iperf3-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
log = "0.4.27"
nix = "0.30.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
